INSERT INTO cliente (fecha, nombre, apellidos, edad, email, telefono) VALUES ('2024-03-20', 'Carlos', 'Ramírez López', 32, 'carlos.ramirez@gmail.com', '688112233');
INSERT INTO cliente (fecha, nombre, apellidos, edad, email, telefono) VALUES ('2024-01-15', 'Lucía', 'Moreno Díaz', 28, 'lucia.moreno@gmail.com', '611223344');
INSERT INTO cliente (fecha, nombre, apellidos, edad, email, telefono) VALUES ('2024-04-05', 'Javier', 'Fernández Ruiz', 35, 'javier.fernandez@gmail.com', '699887766');
INSERT INTO cliente (fecha, nombre, apellidos, edad, email, telefono) VALUES ('2024-02-10', 'Ana', 'Gómez Torres', 24, 'ana.gomez@gmail.com', '622334455');
INSERT INTO cliente (fecha, nombre, apellidos, edad, email, telefono) VALUES ('2024-03-01', 'David', 'Martínez Vargas', 40, 'david.martinez@gmail.com', '655998877');
INSERT INTO cliente (fecha, nombre, apellidos, edad, email, telefono) VALUES ('2024-01-30', 'Marta', 'Sánchez Herrera', 31, 'marta.sanchez@gmail.com', '633445566');
INSERT INTO cliente (fecha, nombre, apellidos, edad, email, telefono) VALUES ('2024-04-12', 'Sergio', 'Navarro Castro', 29, 'sergio.navarro@gmail.com', '677112233');
INSERT INTO cliente (fecha, nombre, apellidos, edad, email, telefono) VALUES ('2024-02-28', 'Elena', 'Ortega Gil', 27, 'elena.ortega@gmail.com', '644556677');
INSERT INTO cliente (fecha, nombre, apellidos, edad, email, telefono) VALUES ('2024-03-18', 'Raúl', 'López Romero', 36, 'raul.lopez@gmail.com', '688334455');
INSERT INTO cliente (fecha, nombre, apellidos, edad, email, telefono) VALUES ('2024-04-20', 'Paula', 'Jiménez Molina', 25, 'paula.jimenez@gmail.com', '600778899');
INSERT INTO cliente (fecha, nombre, apellidos, edad, email, telefono) VALUES ('2024-01-22', 'Alejandro', 'Reyes Martín', 33, 'alejandro.reyes@gmail.com', '699112244');
INSERT INTO cliente (fecha, nombre, apellidos, edad, email, telefono) VALUES ('2024-03-08', 'Clara', 'Domínguez León', 30, 'clara.dominguez@gmail.com', '622778899');
INSERT INTO cliente (fecha, nombre, apellidos, edad, email, telefono) VALUES ('2024-02-19', 'Víctor', 'Pérez Sáez', 34, 'victor.perez@gmail.com', '688445566');
INSERT INTO cliente (fecha, nombre, apellidos, edad, email, telefono) VALUES ('2024-04-03', 'Sara', 'Ruiz Navarro', 26, 'sara.ruiz@gmail.com', '644667788');
INSERT INTO cliente (fecha, nombre, apellidos, edad, email, telefono) VALUES ('2024-01-10', 'Hugo', 'Castro Ramos', 31, 'hugo.castro@gmail.com', '677889900');
INSERT INTO cliente (fecha, nombre, apellidos, edad, email, telefono) VALUES ('2024-02-05', 'Isabel', 'Delgado Peña', 29, 'isabel.delgado@gmail.com', '655667788');
INSERT INTO cliente (fecha, nombre, apellidos, edad, email, telefono) VALUES ('2024-03-27', 'Álvaro', 'Garrido Ibáñez', 38, 'alvaro.garrido@gmail.com', '699334422');
INSERT INTO cliente (fecha, nombre, apellidos, edad, email, telefono) VALUES ('2024-04-18', 'Laura', 'Cabrera Cruz', 22, 'laura.cabrera@gmail.com', '611445566');
INSERT INTO cliente (fecha, nombre, apellidos, edad, email, telefono) VALUES ('2024-01-25', 'Iván', 'Nieto Serrano', 37, 'ivan.nieto@gmail.com', '600223344');
INSERT INTO cliente (fecha, nombre, apellidos, edad, email, telefono) VALUES ('2024-03-13', 'Beatriz', 'Flores Medina', 35, 'beatriz.flores@gmail.com', '633778899');

INSERT INTO rutina (dia_semana, ejercicio, series, repeticiones, peso, cliente_id) VALUES ('Lunes', 'Sentadillas', 4, 12, 60.0, 1);
INSERT INTO rutina (dia_semana, ejercicio, series, repeticiones, peso, cliente_id) VALUES ('Martes', 'Press de banca', 3, 10, 70.0, 2);
INSERT INTO rutina (dia_semana, ejercicio, series, repeticiones, peso, cliente_id) VALUES ('Miércoles', 'Peso muerto', 4, 8, 80.0, 3);
INSERT INTO rutina (dia_semana, ejercicio, series, repeticiones, peso, cliente_id) VALUES ('Jueves', 'Dominadas', 3, 10, 0.0, 4);
INSERT INTO rutina (dia_semana, ejercicio, series, repeticiones, peso, cliente_id) VALUES ('Viernes', 'Press militar', 4, 8, 40.0, 5);
INSERT INTO rutina (dia_semana, ejercicio, series, repeticiones, peso, cliente_id) VALUES ('Sábado', 'Curl bíceps', 3, 12, 15.0, 6);
INSERT INTO rutina (dia_semana, ejercicio, series, repeticiones, peso, cliente_id) VALUES ('Domingo', 'Abdominales', 4, 20, 0.0, 7);
INSERT INTO rutina (dia_semana, ejercicio, series, repeticiones, peso, cliente_id) VALUES ('Lunes', 'Zancadas', 3, 10, 20.0, 8);
INSERT INTO rutina (dia_semana, ejercicio, series, repeticiones, peso, cliente_id) VALUES ('Martes', 'Remo con barra', 4, 8, 60.0, 9);
INSERT INTO rutina (dia_semana, ejercicio, series, repeticiones, peso, cliente_id) VALUES ('Miércoles', 'Press inclinado', 3, 10, 50.0, 10);
INSERT INTO rutina (dia_semana, ejercicio, series, repeticiones, peso, cliente_id) VALUES ('Jueves', 'Elevaciones laterales', 3, 15, 7.5, 1);
INSERT INTO rutina (dia_semana, ejercicio, series, repeticiones, peso, cliente_id) VALUES ('Viernes', 'Press francés', 4, 10, 25.0, 2);
INSERT INTO rutina (dia_semana, ejercicio, series, repeticiones, peso, cliente_id) VALUES ('Sábado', 'Hip thrust', 4, 12, 70.0, 3);
INSERT INTO rutina (dia_semana, ejercicio, series, repeticiones, peso, cliente_id) VALUES ('Domingo', 'Escaladora', 3, 15, 0.0, 4);
INSERT INTO rutina (dia_semana, ejercicio, series, repeticiones, peso, cliente_id) VALUES ('Lunes', 'Burpees', 3, 12, 0.0, 5);
INSERT INTO rutina (dia_semana, ejercicio, series, repeticiones, peso, cliente_id) VALUES ('Martes', 'Mountain climbers', 3, 20, 0.0, 6);
INSERT INTO rutina (dia_semana, ejercicio, series, repeticiones, peso, cliente_id) VALUES ('Miércoles', 'Plancha', 3, 60, 0.0, 7);
INSERT INTO rutina (dia_semana, ejercicio, series, repeticiones, peso, cliente_id) VALUES ('Jueves', 'Peso muerto rumano', 4, 10, 65.0, 8);
INSERT INTO rutina (dia_semana, ejercicio, series, repeticiones, peso, cliente_id) VALUES ('Viernes', 'Fondos en paralelas', 3, 12, 0.0, 9);
INSERT INTO rutina (dia_semana, ejercicio, series, repeticiones, peso, cliente_id) VALUES ('Sábado', 'Extensiones de cuádriceps', 4, 15, 40.0, 10);
